#ifndef env_h
#define env_h

#define ENV_TASK_UART_STACK_SIZE 4096
#define ENV_TASK_UART_PRIORITY 1

#define ENV_TASK_MIDDLEWARE_STACK_SIZE 2048
#define ENV_TASK_MIDDLEWARE_PRIORITY 1

#define ENV_TASK_BOMBA_STACK_SIZE 2048
#define ENV_TASK_BOMBA_PRIORITY 1

#define ENV_TASK_DATA_STACK_SIZE 1024
#define ENV_TASK_DATA_PRIORITY 1

#define ENV_UART_BAUDRATE 115200
#define ENV_UART_RX_GPIO 3
#define ENV_UART_TX_GPIO 1
#define ENV_UART_PORT 0
#define ENV_UART_BUFFER_SIZE 1024

#define ENV_CORE_0 0
#define ENV_CORE_1 1

#define CMD_STATUS 0
#define CMD_BOMBA_PWM 1

#endif
